### ISSUE TITLE
Local Installation Problem (OSError: [E050] Can't find model 'en_core_web_sm')

### ISSUE THREAD

**Issue by wanitchayap** [Computational-Content-Analysis-2020/frequently-asked-questions-spring#2]
running
```
cta2020-setup-user
```
or
```
python -c "import lucem_illud_2020._backend; lucem_illud_2020._backend.makeUser()"
```
give me this error
```
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```
What should I do to fix this?

**Comment by wanitchayap** [comment]
Nevermind! I thought it was some error related to lucem_illud. Turn out it is on spaCy. If anyone has the same problem, you can run this on your terminal beforehand:

```
python3 -m spacy download en_core_web_sm
```

**Comment by DSharm** [comment]
Hi! I had that issue too and resolved it using the same command as you. Now I'm at the "Pushing to GitHub" stage of the setup process which has been taking > 30 minutes. Did yours take a while too?
