### ISSUE TITLE
Web Scraping Tools for Homework 0

### ISSUE THREAD

**Issue by linghui-wu** [Computational-Content-Analysis-2020/frequently-asked-questions-spring#9]
Hello,

Are we allowed to use `selenium` or `scrapy`  instead of `request` to send requests to the URL link and then use `beautifulsoup` to parse over it? I have changed several topics and tried different websites that I want to crawl. Unfortunately, none of them returns the text I need.

Thanks for the assistance in advance!

**Comment by bhargavvader** [comment]
Yes you are, whatever works well for you!
